package edu.missouri.cs.news.api.get_news;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class GetUsers extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2025549795039507711L;

	@Override
	public void init() throws ServletException {
	}

	@Override
	protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		// 设置请求和响应的字符集
		req.setCharacterEncoding("UTF-8");
		resp.setContentType("application/json;charset=UTF-8");

		PrintWriter writer = resp.getWriter();

		String str = "[\n" + "    {\n" + "        \"displayName\":\"McKean, Mike\",\n"
				+ "        \"mail\":\"mckeanml@rjionline.org\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Xu, Shaojie\",\n" + "        \"mail\":\"sxtf8@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Johnson, Bradley Alan\",\n"
				+ "        \"mail\":\"bajxk3@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Won, JiYoung\",\n" + "        \"mail\":\"jwq3f@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Green, Stephanie\",\n"
				+ "        \"mail\":\"sc244@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Guldin, William J.\",\n"
				+ "        \"mail\":\"wjg2q2@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Green, James R.\",\n" + "        \"mail\":\"jrgqkc@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Cawthon, David G.\",\n"
				+ "        \"mail\":\"dgcmbc@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Moore, Shawn\",\n" + "        \"mail\":\"stmf35@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Arndt, Haley E.\",\n"
				+ "        \"mail\":\"heab52@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hiles, Sara\",\n" + "        \"mail\":\"shdzc@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Stephens, Elizabeth Conner\",\n"
				+ "        \"mail\":\"ekcppf@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Kim, Austin\",\n" + "        \"mail\":\"ak2z9@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Brengarth, Lauren\",\n"
				+ "        \"mail\":\"leb34b@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Dulin, Matthew Douglas\",\n"
				+ "        \"mail\":\"mdb62@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hoste, Benjamin\",\n" + "        \"mail\":\"bhd32@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Chen, Jinghong\",\n"
				+ "        \"mail\":\"jc284@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Slivka, Judd\",\n" + "        \"mail\":\"slivkaj@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Greber, Jamie\",\n"
				+ "        \"mail\":\"greberj@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Lamb, Heather\",\n" + "        \"mail\":\"lambh@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Dillard, Allison\",\n"
				+ "        \"mail\":\"dillarda@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Martin Kratzer, Renee\",\n"
				+ "        \"mail\":\"martinkratzerr@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Alvey, Michael (MU-Student)\",\n"
				+ "        \"mail\":\"mganr9@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Kertz, Whitney Sue (MU-Student)\",\n"
				+ "        \"mail\":\"wsk2m9@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Kim, Youngrae . (MU-Student)\",\n"
				+ "        \"mail\":\"ykpf6@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Nelson, Lyndsey Beth (MU-Student)\",\n"
				+ "        \"mail\":\"lbnb62@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Byrne, Paul Robert (MU-Student)\",\n"
				+ "        \"mail\":\"prb399@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Path, Rachel M. (MU-Student)\",\n"
				+ "        \"mail\":\"rmp5yc@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Lukin, Caitlin (MU-Student)\",\n"
				+ "        \"mail\":\"cblb78@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Prothro, Willie T. (MU-Student)\",\n"
				+ "        \"mail\":\"wtp5ff@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Schaff, Megan (MU-Student)\",\n"
				+ "        \"mail\":\"mes994@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Sutherland, Alexander William (MU-Student)\",\n"
				+ "        \"mail\":\"awsutherland@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Ballenger, Tara Alese (MU-Student)\",\n"
				+ "        \"mail\":\"taraballenger@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Malottki, Taylor M. (MU-Student)\",\n"
				+ "        \"mail\":\"tmmc68@mail.umkc.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Mullen, Bridget Leigh (MU-Student)\",\n"
				+ "        \"mail\":\"blm975@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Woodlock, Hollis Marie (MU-Student)\",\n"
				+ "        \"mail\":\"hmw4h9@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Cheng, Eva W.(MU-Student)\",\n"
				+ "        \"mail\":\"wcyqf@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hinsdale, Jenna E. (MU-Student)\",\n"
				+ "        \"mail\":\"jehpp5@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Schmelzer, Elise M. (MU-Student)\",\n"
				+ "        \"mail\":\"eliseschmelzer@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Wohrle, Chase A. (MU-Student)\",\n"
				+ "        \"mail\":\"cawvg5@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Uhlar, Abigail L. (Student)\",\n"
				+ "        \"mail\":\"alutz4@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hagan, Shelly (MU-Student)\",\n"
				+ "        \"mail\":\"mkhghb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Renie, Jacob W. (MU-Student)\",\n"
				+ "        \"mail\":\"jwrkv6@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Streeter, Sianna J. (MU-Student)\",\n"
				+ "        \"mail\":\"siannastreeter@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Rubino, Marissa A. (MU-Student)\",\n"
				+ "        \"mail\":\"mardk7@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Peterkin, Olivia R. (MU-Student)\",\n"
				+ "        \"mail\":\"orp8c4@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Kornhauser, Jacob A. (MU-Student)\",\n"
				+ "        \"mail\":\"jakdp5@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Collins, Allison P. (MU-Student)\",\n"
				+ "        \"mail\":\"apcbqb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Toth, Blake (MU-Student)\",\n"
				+ "        \"mail\":\"btp4f@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Rector, Colette N. (MU-Student)\",\n"
				+ "        \"mail\":\"coletterector@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Nwachukwu, Timothy O. (MU-Student)\",\n"
				+ "        \"mail\":\"tonhh4@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Tucker, Michaela B. (MU-Student)\",\n"
				+ "        \"mail\":\"mbtp8b@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Greenfield, Matthew T. (MU-Student)\",\n"
				+ "        \"mail\":\"mtgt46@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Krebs, Michael J. (MU-Student)\",\n"
				+ "        \"mail\":\"mjkr43@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Manno, Amanda J. (MU-Student)\",\n"
				+ "        \"mail\":\"ajmqmb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Picht, Olivia L. (MU-Student)\",\n"
				+ "        \"mail\":\"olpy96@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Watkins, Sydney A. (MU-Student)\",\n"
				+ "        \"mail\":\"sawg3c@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Trampler, Tori B.(MU-Student)\",\n"
				+ "        \"mail\":\"vbt6z4@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Ryan, Mary Margaret (MU-Student)\",\n"
				+ "        \"mail\":\"maryryan@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Rodriguez, Luisangel (MU-Student)\",\n"
				+ "        \"mail\":\"lrhfb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Satterfield, Kolbie L. (MU-Student)\",\n"
				+ "        \"mail\":\"kls6y5@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Johnson, Kyle N. (MU-Student)\",\n"
				+ "        \"mail\":\"knjfkb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hoffmann, Samantha M. (MU-Student)\",\n"
				+ "        \"mail\":\"smhrvf@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Ruane, Collin P. (MU-Student)\",\n"
				+ "        \"mail\":\"cprrk9@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Sirtori-Cortina, Daniela (MU-Student)\",\n"
				+ "        \"mail\":\"dlswdf@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Weinstock, Alexander (MU-Student)\",\n"
				+ "        \"mail\":\"arwp95@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Bollinger, Alexander J. (MU-Student)\",\n"
				+ "        \"mail\":\"ajbg4c@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Butler, Jennifer (MU-Student)\",\n"
				+ "        \"mail\":\"jbkt2@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Winter, Alexis S. (MU-Student)\",\n"
				+ "        \"mail\":\"aswdfd@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Marlin, Bryce John (MU-Student)\",\n"
				+ "        \"mail\":\"bjm437@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hays, Gabrielle E. (MU-Student)\",\n"
				+ "        \"mail\":\"gehpff@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Reed, Tashan L. (MU-Student)\",\n"
				+ "        \"mail\":\"tlrmrb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Caldwell, Nicole (MU-Student)\",\n"
				+ "        \"mail\":\"ncnq6@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Moeller, Elizabeth (MU-Student)\",\n"
				+ "        \"mail\":\"emgkb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Cowan, Miranda L. (MU-Student)\",\n"
				+ "        \"mail\":\"mlccmf@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Harman, Claire O. (MU-Student)\",\n"
				+ "        \"mail\":\"cohmbc@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Waddell, Jack T. (MU-Student)\",\n"
				+ "        \"mail\":\"jtwf85@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Altvater, Mackenzie K. (MU-Student)\",\n"
				+ "        \"mail\":\"mkaf48@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Rios, Derek D. (MU-Student)\",\n"
				+ "        \"mail\":\"ddryr8@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Dodge, Abigail (MU-Student)\",\n"
				+ "        \"mail\":\"aldd49@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Stubler, Brianna M. (MU-Student)\",\n"
				+ "        \"mail\":\"bms7vd@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Henderson, Justice B. (MU-Student)\",\n"
				+ "        \"mail\":\"jbhxwb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Stanze, Madison H. (MU-Student)\",\n"
				+ "        \"mail\":\"mhstk8@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Larson, Lexi S.(MU-Student)\",\n"
				+ "        \"mail\":\"aslt37@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Fafoglia, Lindsey J. (MU-Student)\",\n"
				+ "        \"mail\":\"ljfdm2@mail.mizzou.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Ronecker, Elizabeth (MU-Student)\",\n"
				+ "        \"mail\":\"err47@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Semke, Brooke (MU-Student)\",\n"
				+ "        \"mail\":\"bstx5@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Miller, Jordyn (MU-Student)\",\n"
				+ "        \"mail\":\"jcmvd3@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Mussman, Phoebe (MU-Student)\",\n"
				+ "        \"mail\":\"plm3m8@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Melvin, Catherine L. (MU-Student)\",\n"
				+ "        \"mail\":\"clm5zb@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Schmittdiel, Matthew H. (MU-Student)\",\n"
				+ "        \"mail\":\"mhsyc4@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Lachnit, Evan (MU-Student)\",\n"
				+ "        \"mail\":\"ejlcm8@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Schlueter, Morgan N. (MU-Student)\",\n"
				+ "        \"mail\":\"mnsf44@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Brown, Jessica Lauren (UMSL-Student)\",\n"
				+ "        \"mail\":\"jlbb63@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Wade, Jenna H. (MU-Student)\",\n"
				+ "        \"mail\":\"jhw7r3@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Marion, Ann J. (MU-Student)\",\n"
				+ "        \"mail\":\"annmarion@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Patel, Keena K. (MU-Student)\",\n"
				+ "        \"mail\":\"kkp26c@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Henderson, Jalyn\",\n" + "        \"mail\":\"jlhm75@mail.missouri.edu\"\n"
				+ "    },\n" + "    {\n" + "        \"displayName\":\"Castulik, Kelsey M. (MU-Student)\",\n"
				+ "        \"mail\":\"kmcmt4@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Sellers, Jessica (MU-Student)\",\n"
				+ "        \"mail\":\"jswx5@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Arger, Alexandra (MU-Student)\",\n"
				+ "        \"mail\":\"ajad49@mail.missouri.edu\"\n" + "    },\n" + "    {\n"
				+ "        \"displayName\":\"Hill, Keeleyshaye G. (MU-Student)\",\n"
				+ "        \"mail\":\"kghr53@mail.missouri.edu\"\n" + "    }\n" + "]";
		writer.write(str);

	}

}
