# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News
  pod 'AFNetworking', '~> 3.0'
  pod 'SnapKit', '~> 3.2.0'
  pod 'PageMenu', '~> 2.0.0'
  pod 'MSGraphSDK'
  pod 'MSGraphSDK-NXOAuth2Adapter'

  target 'NewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
